CREATE DATABASE MUSICA;
GO

USE MUSICA;
GO

CREATE TABLE EMPRESA (
IdEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
Nome_da_Empresa VARCHAR (20) NOT NULL,
);
GO

CREATE TABLE ARTISTA (
IdArtista SMALLINT PRIMARY KEY IDENTITY(1,1),
IdEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(IdEmpresa),
Nome_do_Artista VARCHAR (20) NOT NULL,
);
GO

CREATE TABLE ALBUNS (
IdAlbuns SMALLINT PRIMARY KEY IDENTITY(1,1),
IdArtista SMALLINT FOREIGN KEY REFERENCES ARTISTA(IdArtista),
Nome_do_Album VARCHAR (20) NOT NULL
);
GO

CREATE TABLE ESTILO (
IdEstilo SMALLINT PRIMARY KEY IDENTITY(1,1),
IdAlbuns SMALLINT FOREIGN KEY REFERENCES ALBUNS(IdAlbuns),
Genero VARCHAR (20) NOT NULL
);
GO

CREATE TABLE PLATAFORMA (
IdPlataforma SMALLINT PRIMARY KEY IDENTITY(1,1),
IdAlbuns SMALLINT FOREIGN KEY REFERENCES ALBUNS(IdAlbuns),
Descricao VARCHAR (50) NOT NULL
);
GO

CREATE TABLE USUARIO(
IdUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
IdPlataforma SMALLINT FOREIGN KEY REFERENCES PLATAFORMA(IdPlataforma),
Nome VARCHAR (20) NOT NULL,
Email VARCHAR (20) NOT NULL,
Senha VARCHAR (20) NOT NULL,
);
GO