USE MUSICA
GO

INSERT INTO EMPRESA (Nome_da_Empresa)
VALUES ('NATHCANTORA')

SELECT * FROM EMPRESA

INSERT INTO ARTISTA (IdEmpresa, Nome_do_Artista)
VALUES (1,'NATHALIA NOVAIS'), (1,'PEDRO FIGUEIRA')

SELECT * FROM ARTISTA

INSERT INTO ALBUNS (IdArtista, Nome_do_Album)
VALUES (1,'EVIDENCIAS'),(2,'ALONVBEV') 

SELECT * FROM ALBUNS

INSERT INTO ESTILO (IdAlbuns, Genero)
VALUES (1,'ROMANTICO'), (2,'SERTANEJO')

SELECT * FROM ESTILO

INSERT INTO PLATAFORMA (IdAlbuns, Descricao)
VALUES (1,'SPOTIFYVI'), (2,'DEEZER')

SELECT * FROM PLATAFORMA

INSERT INTO USUARIO (IdPlataforma, Nome, Email, Senha)
VALUES (1, 'PEDRÃO', 'FIGUEIRAPEDRO@GMAIL', 'LALA'), (2, 'NATH', 'NOVAISNATHALIA@GMAIL','LELE')

SELECT * FROM USUARIO

SELECT * FROM EMPRESA
SELECT * FROM ARTISTA
SELECT * FROM ALBUNS
SELECT * FROM ESTILO
SELECT * FROM PLATAFORMA
SELECT * FROM USUARIO