CREATE DATABASE EMPRESA_TARDE
GO

USE EMPRESA_TARDE;
GO

CREATE TABLE PESSOA (
IdPessoa SMALLINT PRIMARY KEY IDENTITY(1,1),
NomePessoa VARCHAR(20)
);
GO

ALTER TABLE PESSOA
DROP COLUMN NomePessoa

ALTER TABLE PESSOA
ADD NomePessoa VARCHAR(20) NOT NULL

CREATE TABLE TELEFONE (
IdTelefone SMALLINT PRIMARY KEY IDENTITY(1,1),
IdPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(IdPessoa),
NumeroTelefone CHAR(20) NOT NULL
);
GO

CREATE TABLE EMAIL (
 IdEmail INT PRIMARY KEY IDENTITY(1,1),
 IdPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(IdPessoa),
 End_Email VARCHAR(256) NOT NULL
);
GO

CREATE TABLE CNH(
 IdCNH SMALLINT PRIMARY KEY IDENTITY(1,1),
 IdPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(IdPessoa),
 Descricao CHAR(11) NOT NULL UNIQUE
);
GO


