USE AUTOMOVEIS_TARDE
GO

INSERT INTO EMPRESA (NomeEmpresa)
VALUES ('HYUNDAI'), ('BMW'), ('MERCEDES')

SELECT * FROM EMPRESA

INSERT INTO VEICULO (IdEmpresa,PlacaVeiculo)
VALUES (1,'324ABCD'),(2,'567LAKC'),(3,'789MASD')
GO

SELECT * FROM VEICULO

INSERT INTO MODELO (IdVeiculo, Modelo_Veiculo)
VALUES (1, 'CRETA'), (2, 'Q3'), (3, 'MERCEDES BENS')
GO

SELECT * FROM MODELO

INSERT INTO MARCA (IdModelo, Marca_Veiculo)
VALUES (1,'HYUNDAI'), (2,'BMW'), (3,'MERCEDES')
GO

SELECT * FROM MARCA

INSERT INTO ALUGUEL (IdVeiculo, Descricao_Aluguel)
VALUES (1,'20/02/2021'), (2,'20/03/2021'), (1,'26/09/2020')
GO

SELECT * FROM ALUGUEL

INSERT INTO CLIENTE (Nome, Cpf)
VALUES ('PEDRÃO','12345678901'), ('NATH','09871234567'), ('MATEUS','09812376545')

SELECT * FROM CLIENTE


SELECT * FROM EMPRESA
SELECT * FROM VEICULO
SELECT * FROM MODELO
SELECT * FROM MARCA
SELECT * FROM ALUGUEL
SELECT * FROM CLIENTE