CREATE DATABASE AUTOMOVEIS_TARDE
GO

USE AUTOMOVEIS_TARDE; 
GO

CREATE TABLE EMPRESA (
IdEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
NomeEmpresa VARCHAR(20) NOT NULL
);

CREATE TABLE VEICULO (
IdVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
IdEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(IdEmpresa),
PlacaVeiculo CHAR(7) NOT NULL
);
GO

CREATE TABLE MODELO (
IdModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
IdVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(IdVeiculo),
Modelo_Veiculo VARCHAR (15) NOT NULL
);
GO

CREATE TABLE MARCA (
IdMarca SMALLINT PRIMARY KEY IDENTITY(1,1),
IdModelo SMALLINT FOREIGN KEY REFERENCES MODELO(IdModelo),
Marca_Veiculo VARCHAR (15) NOT NULL
);
GO

CREATE TABLE CLIENTE (
IdCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
Nome VARCHAR (20) NOT NULL,
Cpf CHAR (11) NOT NULL,
);
GO

DROP TABLE CLIENTE

CREATE TABLE ALUGUEL (
IdAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
IdVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(IdVeiculo),
IdCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE (IdCliente),
Descricao_Aluguel VARCHAR (100) NOT NULL,
);
GO
