
---CRIA UM BANCO DE DADOS
CREATE DATABASE CATALOGO_TARDE;
GO

--DEFINE O BANCO DE DADOS QUE SERA UTILIZADO
USE CATALOGO_TARDE;
GO

CREATE TABLE GENERO (
 IdGenero TINYINT PRIMARY KEY IDENTITY(1,1),
 NomeGenero VARCHAR(20)
);
GO

ALTER TABLE GENERO 
DROP COLUMN NomeGenero

ALTER TABLE GENERO
ADD NomeGenero VARCHAR (20) NOT NULL

CREATE TABLE FILME(
 IdFilme SMALLINT PRIMARY KEY IDENTITY(1,1),
 IdGenero TINYINT FOREIGN KEY REFERENCES GENERO(IdGenero),
 TituloFilme VARCHAR(50) NOT NULL
);
GO



