CREATE DATABASE CLINICA_TARDE
GO

USE CLINICA_TARDE;
GO

CREATE TABLE EMPRESA_CLINICA (
IdClinica SMALLINT PRIMARY KEY IDENTITY(1,1),
Endereco VARCHAR (40) NOT NULL,
);
GO

CREATE TABLE VETERINARIO (
IdVeterinario SMALLINT PRIMARY KEY IDENTITY(1,1),
IdClinica SMALLINT FOREIGN KEY REFERENCES EMPRESA_CLINICA(IdClinica),
Nome VARCHAR (20) NOT NULL,
);
GO

CREATE TABLE DONO (
IdDono SMALLINT PRIMARY KEY IDENTITY(1,1),
Nome_Dono VARCHAR (20) NOT NULL
);
GO

CREATE TABLE TIPO_PET (
IdTipo SMALLINT PRIMARY KEY IDENTITY(1,1),
Tipo_do_Pet VARCHAR (20) NOT NULL,
);
GO

CREATE TABLE RACA (
IdRaça SMALLINT PRIMARY KEY IDENTITY(1,1),
IdTipo SMALLINT FOREIGN KEY REFERENCES TIPO_PET(IdTipo),
Raca_do_Pet VARCHAR (20) NOT NULL
);
GO

CREATE TABLE PET (
IdPet SMALLINT PRIMARY KEY IDENTITY(1,1),
IdDono SMALLINT FOREIGN KEY REFERENCES DONO(IdDono),
IdRaça SMALLINT FOREIGN KEY REFERENCES RACA(IdRaça),
Nome_Pet VARCHAR (20) NOT NULL,
Data_de_Nascimento CHAR (10) NOT NULL,
);
GO

CREATE TABLE CONSULTA (
IdConsuta SMALLINT PRIMARY KEY IDENTITY(1,1),
IdPet SMALLINT FOREIGN KEY REFERENCES PET(IdPet),
IdVeterinario SMALLINT FOREIGN KEY REFERENCES VETERINARIO(IdVeterinario),
Data_Consulta CHAR(10) NOT NULL
);
GO