USE CLINICA_TARDE
GO

INSERT INTO EMPRESA_CLINICA (Endereco)
VALUES ('RUA DARARA')

SELECT * FROM EMPRESA_CLINICA

INSERT INTO VETERINARIO (IdClinica, Nome)
VALUES (1,'PEDRÃO'), (1,'NATHPETS')

SELECT * FROM VETERINARIO

INSERT INTO DONO (Nome_Dono)
VALUES ('PALOMA'), ('MARI')

SELECT * FROM DONO

INSERT INTO TIPO_PET (Tipo_do_Pet)
VALUES ('Cachorro'),('GATO'),('PEIXE')

SELECT * FROM TIPO_PET

INSERT INTO RACA (IdTipo, Raca_do_Pet)
VALUES (1,'GOLDEN'),(2,'VIRALATA'),(3,'PEIXINHO')

SELECT * FROM RACA

INSERT INTO PET (IdRaça, IdDono, Nome_Pet, Data_de_Nascimento)
VALUES (1,1,'AUAU','22/09/2012'),(2,2,'MIAU','12/05/2018'),(3,2,'BLUBLU','27/09/2015')

SELECT * FROM PET

INSERT INTO CONSULTA (IdVeterinario, IdPet, Data_Consulta)
VALUES (1,25,'22/95/2143'), (2,26,'15/12/2125')

SELECT * FROM CONSULTA

SELECT * FROM EMPRESA_CLINICA
SELECT * FROM VETERINARIO
SELECT * FROM DONO
SELECT * FROM TIPO_PET
SELECT * FROM RACA
SELECT * FROM PET
SELECT * FROM CONSULTA